# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_tweet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='author',
        ),
    ]
